### ISSUE TITLE
plot selected resistance on map

### ISSUE THREAD

**Issue by katholt** [amrnet/amrnet#1]
select any genotype, or resistance determinant, to show its frequency on the map (currently we have this for H58 only; and for resistance phenotypes not genotypes)

**Comment by lcerdeira** [comment]
@vLSHTM TASK C

**Comment by vLSHTM** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Map](https://trello.com/c/WEjasmui/8-map)
